image:
  name: zenika/terraform-azure-cli
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ./creds
  - echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
  - terraform init

stages:
  - validate
  - plan
  - apply

variables:
  STATE_ID: "default"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - az login --username="$AZ_USERNAME" --password="$AZ_PASSWORD" --tenant="$AZ_TENANT"
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - az login --username="$AZ_USERNAME" --password="$AZ_PASSWORD" --tenant="$AZ_TENANT"
    - echo "$STATE_ID"
    - STATE_ID=$(az group show --name CHResourceGroup --query id)
    - echo "$STATE_ID"
    - terraform import azurerm_resource_group.rg ${STATE_ID:1:82}
    - terraform apply -auto-approve "planfile"
  dependencies:
    - plan