name: CI/CD pipeline

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  update-docker-images:
    runs-on: ubuntu-latest
    steps:

    # Copy repository code into the environment
    - name: Check out repository code
      uses: actions/checkout@v2

    # Test that docker and docker-compose are installed
    - name: Test docker version
      run: |
        docker --version
        docker-compose --version

    # Login to presonal DockerHub account
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Build the updated docker-compose image
    - name: Build docker-compose image
      run: docker-compose build

    # Push new docker images to DockerHub
    - name: Push docker images to DockerHub
      run: docker-compose push