name: CI/CD pipeline

on:
  push:
    branches: [ feature/terraform-workflow  ]
  pull_request:
    branches: [ main ]

jobs:

  update-docker-images:
    runs-on: ubuntu-latest
    steps:

    # Copy repository code into the environment
    - name: Check out repository code
      uses: actions/checkout@v2

    # Test that docker and docker-compose are installed
    - name: Test docker version
      run: |
        docker --version
        docker-compose --version

    # Login to presonal DockerHub account
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Build the updated docker-compose image
    - name: Build docker-compose image
      run: docker-compose build

    # Push new docker images to DockerHub
    - name: Push docker images to DockerHub
      run: docker-compose push

  deploy-with-terraform:
    needs: update-docker-images
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

    # Validate the current terraform configuration
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    # generates a Terraform plan, This step only runs on pull requests. The PR generates a plan. When the PR is merged, that plan will be applied.
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      continue-on-error: true




  