name: Docker Image Build and Push

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test docker version
      run: docker --version
      run: docker-compose --version