name: Docker Image Build and Push

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test docker
      uses: actions/checkout@v2
    - run: docker --version
    - run: docker-compose --version
  compose:
    runs-on: ubuntu-latest
    steps:
    - name: Compose docker images
      uses: actions/checkout@v2
    - run: docker-compose build