name: Docker Image CI

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test docker
      run: docker info