name: Docker Image Build and Push

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test docker
    - run: docker --version
    - run: docker-compose --version