name: GitHub Action Docker Compose
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buid:
    steps:
      - name: Build the docker images
      - run: echo "this is a test"
      - run: docker-compose build