name: Docker Image Build and Push

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  update-docker-images:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
        uses: actions/checkout@v2
    - name: Test docker version
        run: |
          docker --version
          docker-compose --version
    - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build docker-compose image
        run: docker-compose build