name: Docker Image Build and Push

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  update-docker-images:
    runs-on: ubuntu-latest
    steps:
    - name: Test docker version
      run: |
        docker --version
        docker-compose --version
    - name: Build docker-compose image
      run: docker-compose build