name: Docker Image Build and Push

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  docker-compose build and push:
    runs-on: ubuntu-latest
    steps:
    - name: Test docker version
      run: |
        docker --version
        docker-compose --version